version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: meu-mongo
    restart: always
    ports:
      - 27017:27017
  api:
    image: challenge
    container_name: "springbackendapi"
    ports:
      - "8080:8080"
    links:
      - mongodb

